version: '3.7'

x-es-logging:
  &es-logging
  options:
    max-size: '300m'
    max-file: '2'
  driver: json-file


services:
  indyread-elasticsearch:
    image: ${INDYREAD_ELASTICSEARCH_IMAGE:-docker.elastic.co/elasticsearch/elasticsearch:7.6.1}
    container_name: indyread-elasticsearch
    logging: *es-logging
    networks:
      - esnet
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - indyread-es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  indyread-kibana:
    container_name: indyread-kibana
    image: ${INDYREAD_KIBANA_IMAGE:-docker.elastic.co/kibana/kibana:7.6.1}
    logging: *es-logging
    networks:
      - esnet
    environment:
      - ELASTICSEARCH_HOSTS=http://indyread-elasticsearch.esnet:9200
    ports:
      - 5601:5601
    depends_on:
      - indyread-elasticsearch

networks:
  esnet:
    name: esnet
    driver: bridge

volumes:
  indyread-es:
    driver: local
